[package]
name = "rgraphics"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.18.0", features = ["derive"] }
log = "0.4.22"
rayon = "1.10.0"
softbuffer = "0.4.6"
vek = { version = "0.17.1", features = ["bytemuck", "uvw", "uv", "serde"] }
