[package]
name = "sample-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bytemuck = { version = "1.18.0", features = ["derive"] }
log = "0.4.22"
pretty_env_logger = "0.5.0"
rgraphics = { path = "../rgraphics" }
serde = "1.0.210"
softbuffer = "0.4.6"
winit = "0.30.5"
